#!/bin/bash

###############
# SSH ALIASES #
###############
alias c1='ssh shriwise@tux-c1.cae.wisc.edu'
alias c2='ssh shriwise@tux-c2.cae.wisc.edu'

# AWS ec2 aliases
if [ -f ~/.ssh/pshriwise.pem ]; then
    # production ec2 machine
    alias ec2='ssh -i ~/.ssh/pshriwise.pem ec2'
    # personal ec2 machine
    alias ec2p='ssh -i ~/.ssh/pshriwise.pem ec2p'
fi

alias tux='ssh -X cae'
alias tower='ssh -X home'
alias ff='ssh -X serenity'

