#!/bin/bash


#check to see if a pandora tmux session is already in existence

if [ 0 -eq "$(tmux list-sessions | grep groupme | wc -l )" ] ; then
    #create a pandora tmux and enter it
    echo "Creating tmux for groupme..."
    tmux new -s groupme grpme
else
    echo "Entering groupme..."
    tmux a -t groupme
fi
    
