#!/bin/zsh


py_loc=`which python`
act_py=`ls -al $py_loc | cut -d">" -f2 | sed -e s'/\// /'g | awk '{print $NF}' | sed -e s'/python//'g`
if [[ $act_py == '2.7' ]]; then
  echo "switching to python 3.5"
  sudo port select --set python python35
  sudo port select --set pip pip35
  sudo port select --set sphinx py35-sphinx
  py_loc=`which python`
  act_py=`ls -al $py_loc | cut -d">" -f2 | sed -e s'/\// /'g | awk '{print $NF}' | sed -e s'/python//'g`
  echo "python version is now : $act_py"
elif [[ $act_py == '3.5' ]]; then
  echo "switching to python 2.7"
  sudo port select --set python python27
  sudo port select --set pip pip27
  sudo port select --set sphinx py27-sphinx
  py_loc=`which python`
  act_py=`ls -al $py_loc | cut -d">" -f2 | sed -e s'/\// /'g | awk '{print $NF}' | sed -e s'/python//'g`
  echo "python version is now : $act_py"
else
  echo "Pb dectecting current python version... I get: $act_py"
fi
