#!/bin/zsh
#
function =
{
  echo "$@" | root -l
}
alias calcul="="


function c_git
{

  if [ $# -eq 1 ]; then
    curl -u 'bam241' https://api.github.com/user/repos -d '{"name":"'$@'"}'
    git clone git@github.com:bam241/${@}.git
    cd ${@}
    git-change-url --to-ssh
  else
    if [ ! -d ".git" ]; then
      git init
    fi
    curl -u 'bam241' https://api.github.com/user/repos -d '{"name":"'${PWD##*/}'"}'
    git remote add origin git@github.com:bam241/${PWD##*/}.git
    git-change-url --to-ssh
  fi


}

function gitcd () 
{
  chdir $1;
  if [ -d ".git" ]; then
    git fetch --all -q
  fi
}


function cyclus_release()
{
  export CYCLUS_DIR=$CYCLUS_PATH/cyclus
  export CYCAMORE_DIR=$CYCLUS_PATH/cycamore
  export CYMETRIC_DIR=$CYCLUS_PATH/cymetric
}


