#!/bin/zsh

#############################
# variables d'environnement #
#############################
export MANPATH="/opt/local/share/man"


export PATH="/opt/local/lib"
export PATH="${PATH}:/opt/local/bin"
export PATH="${PATH}:/usr/local/bin"
export PATH="${PATH}:/usr/bin:/bin:"
export PATH="${PATH}:/usr/sbin:/sbin"
export PATH="${PATH}:/opt/X11/bin"
export PATH="${PATH}:/Library/TeX/texbin"

export LANG="en_US.UTF-8"

####---------------------------------------------------####

DEFAULT_USER=mouginot
export MYHOME="/Users/mouginot/work"
export APP_PATH="${MYHOME}/App"

export PATH="${HOME}/.local/bin:$PATH"
export MYHOME="/Users/mouginot/work"
export CYCLUS_PATH="${APP_PATH}/cyclus"

####---------------------------------------------------####







####---------------------------------------------------####
# Compilation

export CC=/opt/local/bin/gcc
export CXX=/opt/local/bin/g++

export CMAKE_MODULE_PATH=/opt/local/include
export CMAKE_PREFIX_PATH=/opt/local


####---------------------------------------------------####


####---------------------------------------------------####
# HDF5

export HDF5_DIR=/opt/local/lib
export HDF5_ROOT=/opt/local/

export PATH="$PATH:${HDF5_DIR}"

####---------------------------------------------------####


####---------------------------------------------------####
# MCNP

#export MCNP_PATH=${APP_PATH}/MCNP

#export PATH=$MCNP_PATH/MCNP_CODE/MCNP6/bin/:${PATH}

####---------------------------------------------------####


####---------------------------------------------------####
# root

export ROOTSYS=$APP_PATH/root
export PATH=${PATH}:${ROOTSYS}/bin
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/Users/mouginot/work/App/root/lib/"

####---------------------------------------------------####


####---------------------------------------------------####
# CLASS package libraries

export CLASS_PATH=${APP_PATH}/CLASS
export CLASS_include=${CLASS_PATH}/source/include
export CLASS_DB=${CLASS_PATH}/Database
export CLASS_lib=${CLASS_PATH}/lib

####---------------------------------------------------####










