#!/bin/zsh

#alias emacs='/opt/local/bin/emacs'
alias emacs='vim'
alias sudo='$HOME/.bin/sudo.sh'
alias py_switch='$HOME/.zsh_config/py_switch'

alias docker_start='source /Applications/Docker/Docker\ Quickstart\ Terminal.app/Contents/Resources/Scripts/start.sh'

alias vim='/opt/local/bin/vim'
alias vi='/opt/local/bin/vim'


export PATH="/Users/mouginot/Library/Python/3.5/bin:${PATH}"
export LD_LIBRARY_PATH="/Users/mouginot/Library/Python/3.5/lib:${LD_LIBRARY_PATH}"
