#!/bin/zsh

##########################
######### Docker #########
##########################
# Kill all running containers.
alias dockerkillall='docker kill $(docker ps -q)'

# Delete all stopped containers.
alias dockercleanc='printf "\n>>> Deleting stopped containers\n\n" && docker rm $(docker ps -a -q)'

# Delete all untagged images.
alias dockercleani='printf "\n>>> Deleting untagged images\n\n" && docker rmi $(docker images -q -f dangling=true)'

# Delete all stopped containers and untagged images.
alias dockerclean='dockercleanc || true && dockercleani'

alias cp='cp -v'
alias xterm='xterm&'
alias ld='ls -ldG'
alias xmgr='xmgrace&'
alias srm='mv -v \!* $HOME/.Trash/'
alias mv='mv -v'
alias ssh='ssh -X'
