#!/bin/bash

shopt -s expand_aliases
source ~/.bashrc

### Script to verify personal confidence that make_watertight is going what its supposed to
OLD_ITER=iter_imprinted.h5m 
OLD_ITER_ZIP=iter_imprinted_zip.h5m 
BLLITE=bllite30matls.h5m
BLLITE_ZIP=bllite30matls.h5m

# Seal older iter model

echo Enter old iter model path:

read OLD_ITER_PATH

if [ "$OLD_ITER_PATH" != "" ]; then 

if [ ! -d $OLD_ITER_PATH ]; then


echo Directory does not exist, exiting...

exit 1

fi

else

echo Skipping Iter Model

fi

echo Enter blanket lite model path:

read BLLITE_PATH

if [ "$BLLITE_PATH" != "" ]; then 

if [ ! -d $BLLITE_PATH ]; then

echo Directory does not exist, exiting...

exit 1

fi

else

echo Skipping the blanket lite model

fi


## Run Tests
echo STARTING TESTS
echo 
if [ "$OLD_ITER_PATH" != "" ]; then 

$HOME/scratch/moab_tools/make_watertight/make_watertight $OLD_ITER_PATH$OLD_ITER

$HOME/scratch/moab_tools/make_watertight/check_watertight $OLD_ITER_PATH$OLD_ITER_ZIP > old_iterresults.txt

fi

if [ "$BLLITE_PATH" != "" ]; then 

$HOME/scratch/moab_tools/make_watertight/make_watertight $BLLITE

$HOME/scratch/moab_tools/make_watertight/check_watertight $BLLITE_ZIP > blresults.txt

fi

echo 
echo TESTING COMPLETE
