#!/bin/bash

###################################
# MACHINE SPECIFIC CONFIGURATIONS #
###################################

MACHINE_NAME="$(hostname)"

if [ "$NO_MACHINE_CONFIG" != "true" ]
then
    if [ -f $HOME/.bash/machines/$MACHINE_NAME ]
    then
        source $HOME/.bash/machines/$MACHINE_NAME;
        if [[ $MACHINE_NAME == "dawn" ]]; then
            MACHINE_ICON="🔆"
        fi
        if [[ $MACHINE_NAME == "dusk" ]]; then
            MACHINE_ICON="🌙"
        fi
        echo "Imported configuration for $MACHINE_NAME $MACHINE_ICON"
    elif [ -d $HOME/.machine/ ]
    then
    MACHINE_NAME="$(ls ~/.machine/)"
    echo "Found dir-based machine name..."
    echo "Importing configuration for $MACHINE_NAME $MACHINE_ICON"
    source $HOME/.bash/machines/$MACHINE_NAME;
    else
        echo "No specific configuration found for $MACHINE_NAME $MACHINE_ICON"
    fi
fi
