#!/bin/bash

###################################
# MACHINE SPECIFIC CONFIGURATIONS #
###################################

# serenity - work machine
MACHINE_NAME="$(hostname)"

if [ $MACHINE_NAME = "serenity" ]
then
    echo "Importing configuration for Serenity"
    source $HOME/.bash/machines/serenity;
fi

