#!/bin/bash

###################################
# MACHINE SPECIFIC CONFIGURATIONS #
###################################

# serenity - work machine
MACHINE_NAME="$(hostname)"

if [ -f $HOME/.bash/machines/$MACHINE_NAME ]
then
    echo "Importing configuration for $MACHINE_NAME"
    source $HOME/.bash/machines/$MACHINE_NAME;
elif [ -d $HOME/.machine/ ]
then
    MACHINE_NAME="$(ls ~/.machine/)"
    if [ "$MACHINE_NAME" == "none" ]
    then
        break
    fi
    echo "Found dir-based machine name..."
    echo "Importing configuration for $MACHINE_NAME"
    source $HOME/.bash/machines/$MACHINE_NAME;
else
    echo "No specific configuration found for $MACHINE_NAME"
fi
