#!/bin/bash

# pyenv variables

export PYENV_ROOT=$HOME/.pyenv/
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

###########################################
### ENVIRONMENTS FOR OTHER APPLICATIONS ###
###########################################
function env_openmc() {
    # EXECUTABLES
    PATH=$HOME/opt/openmc/bin/:$HOME/.local/bin:$PATH

    pyenv shell 3.5.0
    
    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/openmc/lib:$LD_LIBRARY_PATH

    # DATA
    export OPENMC_MULTIPOLE_LIBRARY=$HOME/opt/openmc/xs/wmp_lib/multipole_lib/
    export OPENMC_CROSS_SECTIONS=$HOME/opt/openmc/xs/nndc_hdf5/cross_sections.xml
    export OPENMC_ENDF_DATA=$HOME/opt/openmc/xs/endf-b-vii.1/

    # export environment varialbers
    export_environment_vars

    echo "Adding OpenMC to environment"
}

function env_pyne() {
    # EXECUTABLES
    PATH=$HOME/.local/bin/:$PATH

    pyenv shell 2.7
    
    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH

    PYTHONPATH=$HOME/opt/moab/lib/python2.7/site-packages/:$PYTHONPATH
    
    # export environment varialbers
    export_environment_vars

    echo "Environment set for PyNE development"
}



# convenience for exporting environment variables together
function export_environment_vars() {
    export PATH
    export LD_LIBRARY_PATH
    export HDF5_ROOT
    export PYTHONPATH
}
