#!/bin/bash

# pyenv environment

alias brew='env PATH="${PATH//$(pyenv root)\/shims:/}" brew'
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

###############
# SSH Aliases #
###############
alias anl_vpn="tmux new -d 'ssh homes-gce'"
alias nse_vpn="sshuttle -D --dns -r wiley 0/0"
alias code='open -a "Visual Studio Code"'

# Optional software path
export PATH=$HOME/opt/bin:$PATH
export PATH=/opt/homebrew/opt/pyside@2/bin:$PATH

function env_clang() {
    CLANG_DIR=$HOME/soft/clang
    export PATH=$CLANG_DIR/bin:$PATH
    export LD_LIBRARY_PATH=$CLANG_DIR/lib:$LD_LIBRARY_PATH
    export LIBRARY_PATH=$CLANG_DIR/lib:$LIBRARY_PATH
    export CXX=$CLANG_DIR/bin/clang++
    export CC=$CLANG_DIR/bin/clang
}

function env_openmc() {
    export OPENMC_CROSS_SECTIONS=$HOME/data/xs/openmc/nndc_hdf5/cross_sections.xml
    export OMP_NUM_THREADS=2
}

function env_mamba() {
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/pshriwise/opt/mambaforge3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/pshriwise/opt/mambaforge3/etc/profile.d/conda.sh" ]; then
        . "/Users/pshriwise/opt/mambaforge3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/pshriwise/opt/mambaforge3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/Users/pshriwise/opt/mambaforge3/etc/profile.d/mamba.sh" ]; then
    . "/Users/pshriwise/opt/mambaforge3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

}
