#!/bin/bash

########################
### SERENITY ALIASES ###
########################

tilemill () { /home/shriwise/opt/tilemill/tilemill/index.js $@ ; }
visit () { /home/shriwise/opt/visit/visit2_11_0.linux-x86_64/bin/visit $@ ; }
maple () { /home/shriwiwse/opt/maple2016/bin/xmaple $@ ; }
h5ls () { /home/shriwise/dagmc_blds/hdf5/bin/h5ls $@ ; }
matlab () { /usr/local/bin/matlab $@ ; }
zo () { /home/shriwise/opt/zo/zo.py $@ ; }
notify () { $@; paplay /usr/share/sounds/gnome/default/alerts/bark.ogg; notify-send "$1 is complete"; }

export COWPATH=/home/shriwise/.bash/:/usr/share/cowsay/cows/

####################################
### START NOTEBOOK JEKYLL SERVER ###
####################################
function notebook {

    if [ -d ~/Documents/personal/notebook/ ]; then 
	have_jekyll=$(which jekyll | wc -l)
	if [ $have_jekyll != 0 ]; then
	    tmux new-session -s notebook -d 'cd ~/Documents/personal/notebook/ && jekyll serve -u --host $(dig +short myip.opendns.com @resolver1.opendns.com) --port 4002'
	    echo "Notebook server started."
	    return 0
	else
	    echo "Please install jekyll."
	    return 1
	fi
    else
	echo "Could not locate notebook directory"
	return 1
	fi
}

######################################
### ENVIRONMENT VARIAVBLE SETTINGS ###
######################################
#TRELIS
export TRELIS_PATH=/opt/Trelis-16.3/bin/

# STANDARD PATH VARIABLE
function common_path {
    unset PATH
    # standard system paths
    PATH=$PATH:/usr/local/bin/:/bin/:/usr/bin/
    # embree (Intel ray tracer) programs
    PATH=/home/shriwise/opt/embree/:$PATH
    PATH=/home/shriwise/opt/embree3/:$PATH
    # Intel compiler
    PATH=/home/shriwise/opt/ispc/:$PATH
    # games
    PATH=/usr/games/:$PATH
    # locally installed python probrams
    PATH="/home/shriwise/.local/bin:${PATH}"
    # hpc tookit (profiler from RICE)
    PATH=/home/shriwise/opt/rice/hpc-viewers/hpc-viewer/bin/:$PATH
    PATH=/home/shriwise/opt/rice/hpc-viewers/hpc-trace-viewer/bin/:$PATH
    PATH=/home/shriwise/opt/rice/hpc-toolkit/src/bin/:$PATH
}

# STANDARD LD_LIBRARY_PATH VARIABLE (nothing for now)
function common_ld_library_path {
    unset LD_LIBRARY_PATH
    HDF5_ROOT=$HOME/dagmc_blds/hdf5/
    LD_LIBRARY_PATH=$HOME/dagmc_blds/hdf5/lib:$LD_LIBRARY_PATH
}

function common_pythonpath {
    unset PYTHONPATH
    PYTHONPATH=/home/shriwise/.local/lib/python2.7/site-packages/:$PYTHONPATH
    PYTHONPATH=/home/shriwise/opt/slackbot/:$PYTHONPATH
    PYTHONPATH=$TRELIS_PATH:$PYTHONPATH
    PYTHONPATH=/home/shriwise/.local/bin/:$PYTHONPATH
    
}

function set_common_paths {
    common_path
    common_ld_library_path
    common_pythonpath
}

# convenience for exporting environment variables together 
function export_environment_vars() {
    export PATH
    export LD_LIBRARY_PATH
    export HDF5_ROOT
    export PYTHONPATH
}

function production_sigma {
    #setup the usual paths for the PATH/LD_LIBRARY_PATH
    set_common_paths
    
    # path to DAGMC install
    DAGMC_PATH=$HOME/opt/DAGMC
    LD_LIBRARY_PATH=$TRELIS_PATH:$LD_LIBRARY_PATH
    
    alias trelis='$TRELIS_PATH/trelis -nojournal'

    #MOAB
    PATH=$HOME/opt/MOAB/bin:$PATH
    LD_LIBRARY_PATH=$HOME/opt/MOAB/lib/:$LD_LIBRARY_PATH
    #DAGMC
    PATH=$HOME/opt/DAGMC/bin:$HOME/opt/DAGMC/tools:$PATH
    LD_LIBRARY_PATH=$HOME/opt/DAGMC/lib/:$LD_LIBRARY_PATH

    #DATAPATH FOR XSDIR
    export DATAPATH=/home/shriwise/opt/LANL/mcnp_data/

    # export variables
    export_environment_vars
    
    echo "Environment set for production SIGMA tools."
}

###########################################
### ENVIRONMENTS FOR OTHER APPLICATIONS ###
###########################################
function env_openmc() {    
    # EXECUTABLES
    PATH=/home/shriwise/opt/openmc/bin/:$PATH

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/openmc/lib:$LD_LIBRARY_PATH 
   
    # DATA
    export OPENMC_MULTIPOLE_LIBRARY=/home/shriwise/opt/openmc/xs/wmp_lib/multipole_lib/
    export OPENMC_CROSS_SECTIONS=/home/shriwise/opt/openmc/xs/nndc_hdf5/cross_sections.xml
    export OPENMC_ENDF_SECTIONS=/home/shriwise/opt/openmc/xs/endf-b-vii.1/

    # PYTHON MODULE
    PYTHONPATH=$HOME/.local/lib/python3.5/site-packages/:$PYTHONPATH

    # export environment varialbers
    export_environment_vars
    
    echo "Adding OpenMC to environment"
}

function simd_dagmc() {
    # start with standard variable settings
    set_common_paths
    
    # EXECUTABLES
    # DAGMC
    PATH=$HOME/DAGMC/bin/:$HOME/DAGMC/tools:$PATH
    # SIMD BVH
    PATH=$HOME/opt/MBVH/tools/:$PATH

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/MOAB/lib/:$HOME/DAGMC/lib/:$HOME/opt/MBVH/lib:$LD_LIBRARY_PATH

    # export environment varialbers
    export_environment_vars

    echo "Environment set for SIMD BVH DAGMC"
}
    
################################
### SET STANDARD ENVIRONMENT ###
################################
production_sigma
