#!/bin/bash

# pyenv variables

export PYENV_ROOT=$HOME/.pyenv/
export PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

alias visit='~/opt/visit/visit2_13_1.linux-x86_64/bin/visit'
alias h5sh='~/opt/h5sh/h5sh'
alias trelis='/opt/Trelis-16.3/bin/trelis -nojournal'

alias bear-in-winter='sudo echo "Hibernating..." && gnome-screensaver-command -l && sudo pm-hibernate'

if [ "/bin/bash" != "$BASH" ]; then
    function docker-run-img() {
        docker run -it --net=host -e DISPLAY=$DISPLAY -e XAUTHORITY=$XAUTHORITY -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/shriwise/Downloads:/home/shriwise/Downloads -v $XAUTHORITY $1 /bin/bash
    }

    function _docker-run-img {
        local state

        _arguments -C \
                   '1:images:($(docker images --format "{{.Repository}}:{{.Tag}}" | grep -v "<none>"))' \
                   '*::arg->args'
    }

    compdef _docker-run-img docker-run-img
fi

###########################################
### ENVIRONMENTS FOR OTHER APPLICATIONS ###
###########################################
function env_openmc() {
    # EXECUTABLES
    PATH=$HOME/opt/moab/bin:$PATH
    PATH=$HOME/opt/dagmc/bin/:$HOME/opt/dagmc/tools/:$PATH
    PATH=$HOME/opt/openmc/bin/:$HOME/.local/bin:$PATH
    PATH=$HOME/opt/openmc/openmc/scripts/:$PATH
    PATH=$HOME/opt/njoy/njoy/build:$PATH

    pyenv shell 3.6.6

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/openmc/lib:$LD_LIBRARY_PATH

    # DATA
    export OPENMC_MULTIPOLE_LIBRARY=$HOME/opt/openmc/xs/WMP_Library
    export OPENMC_CROSS_SECTIONS=$HOME/opt/openmc/xs/nndc_hdf5/cross_sections.xml
    export OPENMC_ENDF_DATA=$HOME/opt/openmc/xs/endf-b-vii.1/

    # for testing
    export OMP_NUM_THREADS=2

    # export environment varialbers
    export_environment_vars

    echo "Adding OpenMC to environment"
}

function env_stream() {
    # EXECUTABLES
    PATH=$HOME/opt/moab/bin:$PATH
    PATH=$HOME/opt/dagmc/bin/:$HOME/opt/dagmc/tools/:$PATH
    PATH=$HOME/opt/openmc/bin/:$HOME/.local/bin:$PATH
    PATH=$HOME/opt/openmc/openmc/scripts/:$PATH
    PATH=$HOME/opt/njoy/njoy/build:$PATH

    pyenv shell 3.6.6

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/openmc/lib:$LD_LIBRARY_PATH

    # DATA
    export OPENMC_MULTIPOLE_LIBRARY=$HOME/opt/openmc/xs/WMP_Library
    export OPENMC_CROSS_SECTIONS=$HOME/opt/openmc/xs/jeff-3.2-hdf5/cross_sections.xml
    export OPENMC_ENDF_DATA=$HOME/opt/openmc/xs/endf-b-vii.1/

    # export environment varialbers
    export_environment_vars

    echo "Adding OpenMC to environment"
}


function env_dbldwn() {
    # EXECUTABLES
    PATH=$HOME/opt/moab/bin:$PATH
    PATH=$HOME/opt/dagmc/bin/:$HOME/opt/dagmc/tools/:$PATH
    PATH=$HOME/opt/embree/bin/embree2:$PATH

    pyenv shell 3.5.2

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/embree/lib/:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dbldown/lib:$LD_LIBRARY_PATH
    # export environment varialbers
    export_environment_vars

    echo "Adding Embree/Double-Down to environment"
}


function env_pyne2.7() {
    # EXECUTABLES
    PATH=$HOME/.local/bin/:$PATH

    pyenv shell 2.7.10

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH

    PYTHONPATH=$HOME/opt/moab/lib/python2.7/site-packages/:$PYTHONPATH

    # export environment varialbers
    export_environment_vars

    echo "Environment set for PyNE Python2.7 development"
}

function env_dagviz() {
    # EXECUTABLES
    PATH=$HOME/.local/bin/:$PATH

    pyenv shell 2.7.10

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH

    PYTHONPATH=$HOME/opt/moab/lib/python2.7/site-packages/:$PYTHONPATH
    PYTHONPATH=$HOME/opt/visit/visit2_13_1.linux-x86_64/2.13.1/linux-x86_64/lib/site-packages:$PYTHONPATH

    PATH=$HOME/opt/visit/visit2_13_1.linux-x86_64/bin:$PATH
    # export environment varialbers
    export_environment_vars

    echo "Environment set for PyNE Python2.7 development"
}

function env_pyne3.3() {
    # EXECUTABLES
    PATH=$HOME/.local/bin/:$PATH

    pyenv shell 3.3.4

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH

    PYTHONPATH=$HOME/opt/moab/lib/python3.3/site-packages/:$PYTHONPATH

    # export environment varialbers
    export_environment_vars

    echo "Environment set for PyNE Python3.3 development"
}

function env_plugin() {
     # EXECUTABLES
    PATH=$HOME/opt/trelis-plugin/moab/bin:$PATH
    PATH=$HOME/opt/trelis-plugin/dagmc/bin/:$PATH
    PATH=$HOME/opt/trelis-plugin/dagmc/tools/:$PATH

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/trelis-plugin/moab/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/trelis-plugin/dagmc/lib:$LD_LIBRARY_PATH

    # export environment varialbers
    export_environment_vars

    echo "Environment Set for Trelis plugin development."
}

# convenience for exporting environment variables together
function export_environment_vars() {
    export PATH
    export LD_LIBRARY_PATH
    export HDF5_ROOT
    export PYTHONPATH
}

alias swc_run='docker run -it --net=host -e DISPLAY=:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /home/shriwise/Downloads:/home/shriwise/Downloads swc_python:latest /bin/bash'
