#!/bin/bash

# convenience for exporting environment variables together
function export_environment_vars() {
    export PATH
    export LD_LIBRARY_PATH
}

function env_openfoam_dev() {

    export MPI_ARCH_INC="-I/usr/include/mpich -L/usr/lib/x86_64-linux-gnu"
    export MPI_ARCH_LIBS="-L/usr/lib/x86_64-linux-gnu -lmpich"
    export MPI_ARCH_FLAGS="-Wl,-Bsymbolic-functions -Wl,-z,relro"
    export WM_MPLIB=SYSTEMMPI

    source $HOME/opt/OpenFOAM-dev/etc/bashrc
}

function env_enrico() {
    export FC=/usr/bin/mpifort
    export F90=/usr/bin/mpif90
    export CXX=/usr/bin/mpic++
    export CC=/usr/bin/mpicc
    export HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/serial/

    export OPENMC_CROSS_SECTIONS=$HOME/opt/openmc/xs/lib80x_hdf5/cross_sections.xml
}


function env_cardinal() {
    # set environment for conda MPI compilers
    export FC=/usr/bin/mpifort
    export F90=/usr/bin/mpif90
    export CXX=/usr/bin/mpic++
    export CC=/usr/bin/mpicc
    export HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/serial/
    export LD_LIBRARY_PATH=/home/pshriwise/opt/cardinal/contrib/moose/petsc/arch-moose/lib:$LD_LIBRARY_PATH
    export LD_LIBRARY_PATH=/home/pshriwise/opt/cardinal/cardinal/contrib/moose/libmesh/installed/lib:$LD_LIBRARY_PATH
    export LD_LIBRARY_PATH=/home/pshriwise/opt/cardinal/cardinal/lib:$LD_LIBRARY_PATH

    export NEKRS_HOME=/home/pshriwise/opt/cardinal/cardinal/
    export OPENMC_CROSS_SECTIONS=/home/pshriwise/opt/openmc/xs/nndc_hdf5/cross_sections.xml

    export PATH=/home/pshriwise/opt/cardinal/cardinal/bin:$PATH

    pyenv shell 3.6.6
}

function env_openmc() {
    # EXECUTABLES
    PATH=$HOME/opt/openmc/bin:$PATH
    PATH=$HOME/opt/moab/bin:$PATH
    PATH=$HOME/opt/dagmc/bin:$PATH
    PATH=$HOME/opt/h5sh/:$PATH

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/opt/libmesh/lib/:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/dagmc/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/opt/moab/lib:$LD_LIBRARY_PATH

    # NUCLEAR DATA
    export OPENMC_CROSS_SECTIONS=$HOME/opt/openmc/xs/nndc_hdf5/cross_sections.xml
    export OPENMC_ENDF_DATA=$HOME/opt/openmc/xs/endf-b-vii.1/

    # PYMOAB
    export PYTHONPATH=$HOME/opt/moab/lib/python3.7/site-packages:$PYTHONPATH

    export_environment_vars
    echo "Added OpenMC to environment"
}


function env_dag_openmc_cmp() {
    # EXECUTABLES
    PATH=$HOME/dag_openmc_cmp/miniconda3/envs/openmc_umesh/bin:$PATH
    PATH=$HOME/dag_openmc_cmp/opt/openmc/bin:$PATH
    PATH=$HOME/dag_openmc_cmp/opt/moab/bin:$PATH
    PATH=$HOME/dag_openmc_cmp/opt/dagmc/bin:$PATH
    PATH=$HOME/dag_openmc_cmp/opt/h5sh/:$PATH

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/dag_openmc_cmp/miniconda3/envs/openmc_umesh/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/dag_openmc_cmp/opt/libmesh/lib/:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/dag_openmc_cmp/opt/dagmc/lib:$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$HOME/dag_openmc_cmp/opt/moab/lib:$LD_LIBRARY_PATH

    # NUCLEAR DATA
    export OPENMC_CROSS_SECTIONS=/home/pshriwise/dag_openmc_cmp/opt/openmc/xs/lib80x_hdf5/cross_sections.xml
    export OPENMC_ENDF_DATA=$HOME/dag_openmc_cmp/opt/openmc/xs/endf-b-vii.1/

    # PYMOAB
    export PYTHONPATH=$HOME/dag_openmc_cmp/opt/moab/lib/python3.7/site-packages:$PYTHONPATH

    export_environment_vars

    echo "Added OpenMC to environment"

    conda activate dag_openmc_cmp
    echo "Activated OpenMC w/ DAGMC comparison environment (installs in $HOME/dag_openmc_cmp)"
}

function env_delta () {
    # EXECUTABLES
    PATH=$HOME/delta_tracking/opt/openmc/bin:$PATH

    # SHARED LIBRARIES
    LD_LIBRARY_PATH=$HOME/delta_tracking/miniconda3/envs/openmc_umesh/lib:$LD_LIBRARY_PATH

    # NUCLEAR DATA
    export OPENMC_CROSS_SECTIONS=/home/pshriwise/delta_tracking/opt/openmc/xs/nndc_hdf5/cross_sections.xml
    export OPENMC_ENDF_DATA=$HOME/delta_tracking/opt/openmc/xs/endf-b-vii.1/

    export_environment_vars

    echo "Added OpenMC to environment"

    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"

    if command -v pyenv 1>/dev/null 2>&1; then
        eval "$(pyenv init -)"
    fi

    pyenv shell 3.7.3
    echo "Activated OpenMC Delta Tracking dev environment (installs in $HOME/delta_tracking/opt)"
}

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/pshriwise/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/home/pshriwise/miniconda3/etc/profile.d/conda.sh" ]; then
#         . "/home/pshriwise/miniconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/home/pshriwise/miniconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# <<< Conda initialize <<<
