#!/bin/zsh

# Killer: share history between multiple shells
setopt SHARE_HISTORY
#
# # If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS
#
# # Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS

source $HOME/.bash/zsh/zsh_perso
source $HOME/.bash/zsh/zsh_alias
source $HOME/.bash//zsh/zsh_ohmzsh

alias reset_env='. ~/.zshrc'

##############################
# IMPORT ALL COMMON SETTINGS #
##############################
source $HOME/.bash/common/commonrc

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

########################
# COMPLETION FUNCTIONS #
########################


compdef _travis_trigger_build travis-trigger-build

function _travis_trigger_build() {
    local state

    _arguments -C \
        '1:branches:($(git branch -la 2> /dev/null | sed "s![*/]! !g" | rev | cut -d" " -f1 | rev ))' \
        '2:branches:($(git branch -la 2> /dev/null | sed "s![*/]! !g" | rev | cut -d" " -f1 | rev ))' \
        '*::arg->args'

}
