#!/bin/zsh

# Killer: share history between multiple shells
setopt SHARE_HISTORY
#
# # If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS
#
# # Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS

source $HOME/.bash/zsh/zsh_perso
source $HOME/.bash/zsh/zsh_alias
source $HOME/.bash//zsh/zsh_ohmzsh


##############################
# IMPORT ALL COMMON SETTINGS #
##############################
source $HOME/.bash/common/commonrc
