#!/bin/bash

# if this is a non-interactive login, do nothing
[[ $- != *i* ]] && return

# infinite history
export HISTSIZE=
export HISTFILESIZE=
# don't put duplicate lines or lines starting with space in the history.
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


### Include Git Aware Prompt ###
export GITAWAREPROMPT=~/.bash/bash/
if [ "$NO_GIT_PROMPT" != "true" ]; then
    source $GITAWAREPROMPT/prompt.sh
fi

#keybinding addition
if [ "$TERM" == "xterm" ]; then
    bind '"\C-H":backward-kill-word'
fi

###############################
# OTHER BASH-SPECIFIC DETAILS #
###############################
source $HOME/.bash/bash/details

##############################
# IMPORT ALL COMMON SETTINGS #
##############################
source $HOME/.bash/common/commonrc
source ~/.bash/common/commonrc
